name: regression-tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push events
  push:
    branches: [ 'main' ]
    tags-ignore: [ '**' ]

  # Triggers the workflow on pull request events
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  regression_tests:
    name: Python ${{ matrix.python-version }}

    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false  # false: try to complete all jobs
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone CLOUDSC
        uses: actions/checkout@v4
        with:
          repository: ecmwf-ifs/dwarf-p-cloudsc
          path: cloudsc
          ref: develop

      - name: Clone ECWAM
        uses: actions/checkout@v4
        with:
          repository: ecmwf-ifs/ecwam
          path: ecwam
          ref: develop-1.3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Refresh package lists
        run: |
          sudo apt-get -o Acquire::Retries=3 update || true

      - name: Install Loki dependencies
        run: |
          sudo apt-get -o Acquire::Retries=3 install -y graphviz gfortran

      - name: Install OMNI + CLAW dependencies
        run: |
          sudo apt-get -o Acquire::Retries=3 install -y byacc flex openjdk-11-jdk cmake ant

      - name: Install CLOUDSC dependencies
        run:
          sudo apt-get -o Acquire::Retries=3 install -y libhdf5-dev

      - name: Install Loki
        run: |
          export JAVA_HOME=${JAVA_HOME_11_X64}
          ./install --with-omni --with-ofp --with-tests --without-dace
          echo "export JAVA_HOME=${JAVA_HOME_11_X64}" >> loki-activate

      - name: Install up-to-date CMake
        run: |
          source loki-activate
          pip install cmake

      - name: Install ECWAM dependencies
        run: |
          sudo apt-get -o Acquire::Retries=3 install -y libopenmpi-dev
          pip install pyyaml fypp

      - name: Run CLOUDSC and ECWAM regression tests
        env:
          CLOUDSC_DIR: ${{ github.workspace }}/cloudsc
          ECWAM_DIR: ${{ github.workspace }}/ecwam
          OMP_STACKSIZE: 4G
        run: |
          source loki-activate
          pytest --pyargs loki.transformations -k 'cloudsc or ecwam'
